### PR TITLE
Add android_frameworks_base repo

### PR DESCRIPTION
**Pull request by Roboe**
It would be great to have it here for reference.

There is work being done at @WeAreFairphone to backport Fairphone OS's lockscreen clock widget functionality (at `packages/Keyguard`) to the standalone Clock Widget.

### CODE REVIEW

**Comment by z3ntu** [comment]
Looks good, thanks.

**Comment by z3ntu** [comment]
The mirror will take at least until tomorrow because the repo is over 1.5GB and the SD card of my raspberry pi responsible for the mirror only has about 700MB left. Will figure out a solution tomorrow.

**Comment by Roboe** [comment]
Oops, sorry for your little pi, 😀
Ok, no problem.

**Comment by z3ntu** [comment]
Mirror should be up in probably 10 minutes. I have transferred the bot things to my Raspberry Pi 3 which has a bigger sd card. :)

**Comment by z3ntu** [comment]
Surprise, it's online now 😉 uploading 1.5GB takes quite a long time especially if git just stops uploading halfway through the process...

**Comment by Roboe** [comment]
Sorry for the hassle, Luca. I didn't foresight that single line could cause such troubles, hehe.

Thank you so much! :D

**Pull request merged**
